name: thusovhathuni
description: Personal health companion for chronic conditions (Flutter mobile)
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3
  path: ^1.9.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


